name: Custom Workflow

on:
  push:
    branches:
      - main
      - develop
      - features/*
env:
  PROD_PYTHON_SCRIPT: "Hello, World!"
  PROD_JSON_CONFIGURATION: "123"
  REPO_NAME: env.GITHUB_REPOSITORY

jobs:
  my_custom_job:
    runs-on: ubuntu-latest

    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2

      - name: Set up AWS configuration
        run: |
          # Set up AWS CLI configuration (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, etc.)

      - name: test aws connection
        run: |
          #try an ls to test connection
#      - name: Check if Glue Job already exists
#        run: |
#          job_name="your-job-name"
#
#          job_info=$(aws glue get-job --job-name "$job_name" 2>&1)
#          if [ $? -eq 0 ]; then
#            echo "Job $job_name exists:"
#            echo "$job_info"
#          else
#            echo "Job $job_name does not exist."
#          fi
      - name: Run Custom Function
        run: |
          # You can write your custom logic here
          echo "Running my custom function..."
          # You can call other scripts or functions as needed

      - name: Build application
        run: |
          # Custom build commands
          echo "Building application..."

      - name: Deploy application
        run: |
          # Custom deployment commands
          echo "Deploying application..."
      - name: Set Repository Name
        id: set_repo_name
        run: echo "::set-output name=repo_name::$(basename $GITHUB_REPOSITORY)"

      - name: Print Repository Name
        run: echo "repo = ${{ steps.set_repo_name.outputs.repo_name }}"
